/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.5.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package hu.hollo.news.api

import hu.hollo.news.model.dto.UserCredentialsDto
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*
import javax.validation.Valid

@Validated
@RequestMapping("\${api.base-path:}")
interface UserApi {


    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/user/login"],
            produces = ["text/plain"],
            consumes = ["application/json"]
    )
    fun loginUser( @Valid @RequestBody userCredentialsDto: UserCredentialsDto): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
