/**
 * Service Search App REST API documentation
 * This file holds the REST API documentation of the Hollo Event Notifier project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { EventDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EventsApiServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create new event
     * 
     * @param eventDto event to create
     */
    createEvent(eventDto: EventDto, extraHttpRequestParams?: any): Observable<EventDto>;

    /**
     * Deletes event with given ID
     * 
     * @param id UUID of event to delete
     */
    deleteEventById(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Provides an event with the corresponding id
     * 
     * @param id UUID of requested event
     */
    getEventById(id: string, extraHttpRequestParams?: any): Observable<EventDto>;

    /**
     * Provides all events between given start-date and end-date
     * 
     * @param startDate Start date of time intervall
     * @param endDate End date of time intervall
     */
    getEvents(startDate: string, endDate: string, extraHttpRequestParams?: any): Observable<Array<EventDto>>;

    /**
     * Updates event with given ID
     * 
     * @param id UUID of event to update
     * @param eventDto event to update
     */
    updateEventById(id: string, eventDto: EventDto, extraHttpRequestParams?: any): Observable<EventDto>;

}
