/**
 * Service Search App REST API documentation
 * This file holds the REST API documentation of the Hollo Event Notifier project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This DTO represents an event in the dormitory
 */
export interface EventDto { 
    title: string;
    place: string;
    organizer: string;
    hasPoints: boolean;
    startDate: string;
    endDate: string;
    link?: string;
    id?: string;
}

